name: manage-azure-policy-983bc39c
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/_Preview_Certificates_should_have_the_specified_lifetime_action_triggers_12ef42cb-9903-4e39-9c26-422d29570417/**'
#      - .github/workflows/manage-azure-policy-983bc39c.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_983bc39c}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/_Preview_Certificates_should_have_the_specified_lifetime_action_triggers_12ef42cb-9903-4e39-9c26-422d29570417/**
